version:
  name: velociraptor
  version: 0.6.9
  commit: be0af2d
  build_time: "2023-05-24T23:33:19Z"
  install_time: 1688721218
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/5074403308
  compiler: go1.20.4
Client:
  server_urls:
  - https://10.10.0.99:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRALBO3yxyF1vAsewSLelxUsMwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIzMDcwNzA5MTQwN1oXDTMz
    MDcwNDA5MTQwN1owGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqLLLBl+ScESnTmh/PjCgxcu2lXIGCjDw
    uOVkhG66KxBscMx0DXIH+RbW2QxYRu5AQbznbQWqOTMgNT9VA0MmlaSaCQUI3l6v
    2fmzYppPKDJeXIgp1/ndQaNV/uM4fpsH3mFJ+NBm2rS9scBVU4oQajNCXEg8y6W0
    2Q9dG2yH5lUc+NWD7prFXzsg0rgSNvWbO7MXhudPgGPZ92VPkzl3eTRf+e46pd8z
    6uyCJn6mYFfK3WKgLyXYPE0wvjnMSxWwvWPi/pjVdi9CxvhwJlocGJmmz5bMls9a
    lk2l0ZQkuOPMQZB1ahsD/HVQID5E3Wq5yCfbkB0h8CAw6hbCLiEECwIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUw5TAS8kN+Md6Hz53sVMAUZv3
    q2gwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAJxHkt22VLWvCiTcIhNB0Dob7M6rhPmbJa9l5RqPME/Y
    K1AnVegtflplAsR5f0P+k5SnHK5YdAKtZfrI5h2Jy9vJIunXeFJAj8bzDoKZhN2Y
    ZV7cXX9XC01Ryx8FNzJY/xKWVvBQ0P9Wadg3HE/tvVwjOmMME87aInce6e/lGcOP
    vB/F52l/Dm8vrpHhTp2JRJLLHxP+rO5/VRAdkTbIH+jSgl7mp8dnCRMSj8oVOVrP
    BiOSytLA5DV6UCEDLRPQO4DdIwROnYO0tDiSoDbVF4sXxmzb6QGu/ETc/ubMpCl2
    y6gnCDkyr7ZkhD755hDwgxj+H/k7GtoKbBKyAZDTtF4=
    -----END CERTIFICATE-----
  nonce: CMSFYGDFClI=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.9
    commit: be0af2d
    build_time: "2023-05-24T23:33:19Z"
    install_time: 1688721218
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/5074403308
    compiler: go1.20.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin

